<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_Staff</name>
   <tag></tag>
   <elementGuidId>9c748cef-7f6a-480b-8554-86518753f567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//form//input[   not(@type='hidden')   and contains(@style,'display')   and @required ])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uOlyc1v</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b82599a2-8dd2-47a0-848f-b03795ebc0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uOlyc1v</value>
      <webElementGuid>63eaffc2-e838-4f1e-b052-87f75beff15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uOlyc1v</value>
      <webElementGuid>198b0872-b05d-4914-ac2f-0b87552fefce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uOlyc1v&quot;)</value>
      <webElementGuid>ab11f7b1-8eb0-4165-ad48-3461bbae9f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uOlyc1v']</value>
      <webElementGuid>3d69206a-2654-40cc-aafb-fc0d4836590d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/input[3]</value>
      <webElementGuid>0f52aba6-5a29-4da1-9e9c-7ef5e846409a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>0c0df56d-9d74-4688-88e2-48019697547a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uOlyc1v' and @name = 'uOlyc1v']</value>
      <webElementGuid>419cdc74-86f1-41d9-bdb5-c759541a6ae9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
